config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  root 'home#index'

  devise_for :usuarios, path: 'admin', path_names: { sign_in: 'entrar', sign_out: 'sair' }
  namespace :admin do
    resources :usuarios
    resources :funcionarios
    resources :setors
    resources :unidades
    resources :cargos
    resources :secretarias
  end


  devise_for :funcionarios, path: 'funcionario', path_names: { sign_in: 'entrar', sign_out: 'sair' }
  namespace :funcionarios do
    resources :visitas
    resources :visitantes
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get 'visitantes/consultar' => 'visitantes#consultar_visitante'
  post 'visitas/registrar' => 'visitas#registrar'
  post 'visitas/registrar' => 'visitas#registrar_visita'
  get 'admin' => 'admin#index'
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/secretaria.rb
class Secretaria < ApplicationRecord
  has_many :unidades
  has_many :funcionarios
end

app/controllers/admin/secretarias_controller.rb
module Admin
class SecretariasController < AdminController
  before_action :set_secretaria, only: %i[ show edit update destroy ]

  # GET /secretarias or /secretarias.json
  def index
    @secretarias = Secretaria.all
  end

  # GET /secretarias/1 or /secretarias/1.json
  def show
  end

  # GET /secretarias/new
  def new
    @secretaria = Secretaria.new
  end

  # GET /secretarias/1/edit
  def edit
  end

  # POST /secretarias or /secretarias.json
  def create
    @secretaria = Secretaria.new(secretaria_params)

    respond_to do |format|
      if @secretaria.save
        format.html { redirect_to admin_secretaria_url(@secretaria), notice: "Secretaria was successfully created." }
        format.json { render :show, status: :created, location: @secretaria }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @secretaria.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /secretarias/1 or /secretarias/1.json
  def update
    respond_to do |format|
      if @secretaria.update(secretaria_params)
        format.html { redirect_to admin_secretaria_url(@secretaria), notice: "Secretaria was successfully updated." }
        format.json { render :show, status: :ok, location: @secretaria }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @secretaria.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /secretarias/1 or /secretarias/1.json
  def destroy
    @secretaria.destroy!

    respond_to do |format|
      format.html { redirect_to admin_secretarias_path, notice: "Secretaria was successfully destroyed." }
      format.json { head :no_content }
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_secretaria
      @secretaria = Secretaria.find_by(id: params[:id])

      unless @secretaria
        flash[:alert] = 'Secretaria não encontrada'
        redirect_to admin_secretarias_path
      end
    end

    # Only allow a list of trusted parameters through.
    def secretaria_params
      params.require(:secretaria).permit(:nome)
    end
end
end

app/helpers/secretaria_helper.rb
module SecretariaHelper
end

app/helpers/secretarias_helper.rb
module SecretariasHelper
end

app/views/admin/secretarias/_form.html.erb
<%= form_with(model: secretaria, url: secretaria.persisted? ? admin_secretaria_path(secretaria) : admin_secretarias_path, method: secretaria.persisted? ? :patch : :post) do |form| %>
  <% if secretaria.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(secretaria.errors.count, "error") %> Não foi possível salvar essa Secretaria:</h2>
      <ul>
        <% secretaria.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/secretarias/_secretaria.html.erb
<div id="<%= dom_id secretaria %>">
  <p>
    <strong>Nome:</strong>
    <%= secretaria.nome %>
  </p>

</div>

app/views/admin/secretarias/edit.html.erb
<h1>Editar Secretaria</h1>

<%= render "form", secretaria: @secretaria %>

<br>

<div>
  <%= link_to "Visualizar essa Secretaria", admin_secretaria_path(@secretaria) %>
  |
  <%= link_to "Voltar para todas as Secretarias", admin_secretarias_path %>
</div>

app/views/admin/secretarias/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Secretarias</h1>

<div id="secretarias">
  <% @secretarias.each do |secretaria| %>
    <%= render secretaria %>
    <p>
  <%= link_to "Visualizar Secretaria", admin_secretaria_path(secretaria) %>
</p>
  <% end %>
</div>

<%= link_to "Criar nova Secretaria", new_admin_secretaria_path %>

<br>
<br>
<%= link_to "Voltar para página Inicial", admin_path %>

app/views/admin/secretarias/new.html.erb
<h1>Nova Secretaria</h1>

<%= render "form", secretaria: @secretaria %>

<br>

<div>
  <%= link_to "Voltar para todas as Secretarias", admin_secretarias_path %>
</div>

app/views/admin/secretarias/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @secretaria %>

<div>
  <%= link_to "Editar Secretaria", edit_admin_secretaria_path(@secretaria) %> |
  <%= link_to "Voltar para todas as Secretarias", admin_secretarias_path %>

  <%= button_to "Excluir Secretaria", admin_secretaria_path(@secretaria), method: :delete %>
</div>