config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  root 'home#index'

  devise_for :usuarios, path: 'admin', path_names: { sign_in: 'entrar', sign_out: 'sair' }
  namespace :admin do
    resources :usuarios
    resources :funcionarios
    resources :setors
    resources :unidades
    resources :cargos
    resources :secretarias
  end


  devise_for :funcionarios, path: 'funcionario', path_names: { sign_in: 'entrar', sign_out: 'sair' }
  namespace :funcionarios do
    resources :visitas
    resources :visitantes
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get 'visitantes/consultar' => 'visitantes#consultar_visitante'
  post 'visitas/registrar' => 'visitas#registrar'
  post 'visitas/registrar' => 'visitas#registrar_visita'
  get 'admin' => 'admin#index'
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cargo.rb
class Cargo < ApplicationRecord
  has_many :funcionarios
  has_many :usuarios
end

app/models/funcionario.rb
class Funcionario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  belongs_to :setor
  belongs_to :cargo
  belongs_to :secretaria
  belongs_to :unidade

  validates :nome, presence: true
  validates :cpf, presence: true, uniqueness: true
  validates :rg, presence: true
  validates :telefone, presence: true
end

app/models/secretaria.rb
class Secretaria < ApplicationRecord
  has_many :unidades
  has_many :funcionarios
end

app/models/setor.rb
class Setor < ApplicationRecord
  belongs_to :unidade
  belongs_to :secretaria
  has_many :funcionarios
end

app/models/unidade.rb
class Unidade < ApplicationRecord
  belongs_to :secretaria
  has_many :funcionarios
end

app/models/usuario.rb
class Usuario < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum tipo: [:admin, :funcionario, :atendente]


end

app/models/visitante.rb
class Visitante < ApplicationRecord
  has_many :visitas
  mount_uploader :foto, FotoUploader
  validates :cpf, presence: true, uniqueness: true
end

app/models/visitum.rb
class Visitum < ApplicationRecord
  belongs_to :visitante
  belongs_to :funcionario
  belongs_to :setor

  validates :data_hora, :setor, presence: true
end

app/controllers/admin/unidades_controller.rb
module Admin
class UnidadesController < AdminController
  before_action :set_unidade, only: %i[ show edit update destroy ]

  # GET /unidades or /unidades.json
  def index
    @unidades = Unidade.all
  end

  # GET /unidades/1 or /unidades/1.json
  def show
  end

  # GET /unidades/new
  def new
    @unidade = Unidade.new
  end

  # GET /unidades/1/edit
  def edit
  end

  # POST /unidades or /unidades.json
  def create
    @unidade = Unidade.new(unidade_params)

    respond_to do |format|
      if @unidade.save
        format.html { redirect_to admin_unidade_url(@unidade), notice: "Unidade was successfully created." }
        format.json { render :show, status: :created, location: @unidade }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @unidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unidades/1 or /unidades/1.json
  def update
    respond_to do |format|
      if @unidade.update(unidade_params)
        format.html { redirect_to admin_unidade_url(@unidade), notice: "Unidade was successfully updated." }
        format.json { render :show, status: :ok, location: @unidade }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @unidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unidades/1 or /unidades/1.json
  def destroy
    @unidade.destroy!

    respond_to do |format|
      format.html { redirect_to admin_unidades_url, notice: "Unidade was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unidade
      @unidade = Unidade.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def unidade_params
      params.require(:unidade).permit(:nome, :secretaria_id)
    end
end
end

app/controllers/admin_controller.rb
class AdminController < ActionController::Base    
  protect_from_forgery prepend: true, with: :exception
  protect_from_forgery prepend: true, with: :null_session, if: proc { |c| c.request.format == 'application/json' }  

  after_action :flash_to_headers
  before_action :authenticate_usuario!

  helper_method :current_user 

  def index;end

  def flash_to_headers
      return unless request.xhr?
      response.headers['X-Message'] = flash_message
      response.headers["X-Message-Type"] = flash_type.to_s
      flash.discard # don't want the flash to appear when you reload page
  end

  protected
      def current_user
          current_usuario 
      end

  private
      def flash_message
          [:error, :warning, :notice].each do |type|
              return flash[type] unless flash[type].blank?
          end
      end

      def flash_type
          [:error, :warning, :notice].each do |type|
              return type unless flash[type].blank?
          end
      end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_funcionario!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/secretaria_helper.rb
module SecretariaHelper
end

app/helpers/secretarias_helper.rb
module SecretariasHelper
end

app/helpers/setors_helper.rb
module SetorsHelper
end

app/helpers/unidades_helper.rb
module UnidadesHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/visitantes_helper.rb
module VisitantesHelper
end

app/helpers/visitas_helper.rb
module VisitasHelper
end

app/views/admin/unidades/_form.html.erb
<%= form_with(model: [:admin, unidade], url: admin_unidades_path, method: :post) do |form| %>
  <% if unidade.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(unidade.errors.count, "error") %> Não foi possível salvar essa Unidade:</h2>
      <ul>
        <% unidade.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>

<% end %>


  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :secretaria_id %>
    <%= form.collection_select :secretaria_id, Secretaria.all, :id, :nome, { prompt: 'Selecione uma secretaria' } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/unidades/_unidade.html.erb
<div id="<%= dom_id unidade %>">
  <p>
    <strong>Nome:</strong>
    <%= unidade.nome %>
  </p>

  <p>
    <strong>Secretaria:</strong>
    <%= unidade.secretaria_id %>
  </p>

</div>

app/views/admin/unidades/edit.html.erb
<h1>Editar Unidade</h1>

<%= render "form", unidade: @unidade %>

<br>

<div>
  <%= link_to "Visualizar Unidade", admin_unidade_path(@unidade) %> |
  <%= link_to "Voltar para todas as Unidades", admin_unidades_path %>
</div>

app/views/admin/unidades/index.html.erb
<!-- app/views/unidades/index.html.erb -->
<p style="color: green"><%= notice %></p>

<h1>Unidades</h1>

<div id="unidades">
  <% @unidades.each do |unidade| %>
    <p><strong>Nome:</strong> <%= unidade.nome %></p>
    <p><strong>Secretaria:</strong> <%= unidade.secretaria.nome %></p>
    <p>
      <%= link_to "Visualizar Unidade", admin_unidade_path(unidade) %>
    </p>
  <% end %>
</div>

<%= link_to "Criar nova Unidade", new_admin_unidade_path %>
<br>
<br>
<%= link_to "Voltar para página Inicial", admin_path %>

app/views/admin/unidades/new.html.erb
<h1>Nova Unidade</h1>

<%= render "form", unidade: @unidade %>

<br>

<div>
  <%= link_to "Voltar para todas as Unidades ", admin_unidades_path %>
</div>

app/views/admin/unidades/show.html.erb
<!-- app/views/admin/unidades/show.html.erb -->
<p style="color: green"><%= notice %></p>

<h1>Unidade</h1>

<div id="unidade">
  <p><strong>Nome:</strong> <%= @unidade.nome %></p>
  <p><strong>Secretaria:</strong> <%= @unidade.secretaria.nome %></p>

  <div>
    <%= link_to "Editar essa Unidade", edit_admin_unidade_path(@unidade) %> |
    <%= link_to "Voltar para todas as Unidades", admin_unidades_path %>
  </div>

  <%= button_to "Excluir Unidade", admin_unidade_path(@unidade), method: :delete %>

</div>