config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  root 'home#index'

  devise_for :usuarios, path: 'admin', path_names: { sign_in: 'entrar', sign_out: 'sair' }
  namespace :admin do
    resources :usuarios
    resources :funcionarios
    resources :setors
    resources :unidades
    resources :cargos
    resources :secretarias
  end


  devise_for :funcionarios, path: 'funcionario', path_names: { sign_in: 'entrar', sign_out: 'sair' }
  namespace :funcionarios do
    resources :visitas
    resources :visitantes
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get 'visitantes/consultar' => 'visitantes#consultar_visitante'
  post 'visitas/registrar' => 'visitas#registrar'
  post 'visitas/registrar' => 'visitas#registrar_visita'
  get 'admin' => 'admin#index'
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/funcionario.rb
class Funcionario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  belongs_to :setor
  belongs_to :cargo
  belongs_to :secretaria
  belongs_to :unidade

  validates :nome, presence: true
  validates :cpf, presence: true, uniqueness: true
  validates :rg, presence: true
  validates :telefone, presence: true
end

app/controllers/admin/funcionarios_controller.rb
module Admin
class FuncionariosController < AdminController
  before_action :set_funcionario, only: %i[ show edit update destroy ]

  # GET /funcionarios or /funcionarios.json
  def index
    @funcionarios = Funcionario.all
  end

  # GET /funcionarios/1 or /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
    @cargos_disponiveis = Cargo.all
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios or /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to admin_funcionario_url(@funcionario), notice: "Funcionario was successfully created." }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1 or /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to admin_funcionario_url(@funcionario), notice: "Funcionario was successfully updated." }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1 or /funcionarios/1.json
  def destroy
    @funcionario.destroy!

    respond_to do |format|
      format.html { redirect_to admin_funcionarios_url, notice: "Funcionario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def funcionario_params
      params.require(:funcionario).permit(:nome, :cpf, :rg, :telefone, :setor_id, :cargo_id, :secretaria_id, :unidade_id, :email, :password)
    end
end
end

app/controllers/funcionarios/confirmations_controller.rb
# frozen_string_literal: true

class Funcionarios::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/funcionarios/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Funcionarios::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/funcionarios/passwords_controller.rb
# frozen_string_literal: true

class Funcionarios::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/funcionarios/registrations_controller.rb
# frozen_string_literal: true

class Funcionarios::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/funcionarios/sessions_controller.rb
# frozen_string_literal: true

class Funcionarios::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/funcionarios/unlocks_controller.rb
# frozen_string_literal: true

class Funcionarios::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/funcionarios/visitantes_controller.rb
module Funcionarios
  class VisitantesController < ApplicationController
  before_action :set_visitante, only: %i[ show edit update destroy ]

  # GET /visitantes or /visitantes.json
  def index
    @visitantes = Visitante.all
  end

  # GET /visitantes/1 or /visitantes/1.json
  def show
  end

  # GET /visitantes/new
  def new
    @visitante = Visitante.new
  end

  # GET /visitantes/1/edit
  def edit
  end

  # POST /visitantes or /visitantes.json
  def create
    @visitante = Visitante.new(visitante_params)

    respond_to do |format|
      if @visitante.save
        format.html { redirect_to funcionarios_visitante_url(@visitante), notice: "Visitante was successfully created." }
        format.json { render :show, status: :created, location: @visitante }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @visitante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitantes/1 or /visitantes/1.json
  def update
    @visitante = Visitante.find(params[:id])

    if @visitante.update(visitante_params)
      redirect_to alguma_rota_path, notice: 'Visitante foi atualizado com sucesso.'
    else
      render :edit
    end
  end

  # DELETE /visitantes/1 or /visitantes/1.json
  def destroy
    @visitante.destroy!

    respond_to do |format|
      format.html { redirect_to funcionarios_visitantes_url, notice: "Visitante was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitante
      @visitante = Visitante.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def visitante_params
      params.require(:visitante).permit(:nome, :cpf, :rg, :telefone, :foto)
    end

    def consultar_visitante
      cpf = params[:cpf]
      @visitante = Visitante.find_by(cpf: cpf)

      if @visitante
        # Exibir detalhes do visitante
        render 'consultar'
      else
        # Redirecionar para a página de cadastro de visitantes ou exibir uma mensagem adequada
        flash[:alert] = 'Visitante não encontrado.'
        redirect_to new_visitante_path

      end
    end
  end
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/views/funcionarios/_form.html.erb
<%= form_with(model: [:admin, funcionario], local: true) do |form| %>

  <% if funcionario.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(funcionario.errors.count, "error") %> Não foi possível salvar esse Funcionário:</h2>

      <ul>
        <% funcionario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :rg, style: "display: block" %>
    <%= form.text_field :rg %>
  </div>

  <div class="field">
    <%= form.label :telefone, style: "display: block" %>
    <%= form.text_field :telefone %>
  </div>

  <div class="field">
    <%= form.label :secretaria_id, style: "display: block" %>
    <%= form.collection_select :secretaria_id, Secretaria.all, :id, :nome, prompt: "Selecione uma secretaria" %>
  </div>

  <div class="field">
    <%= form.label :unidade_id, style: "display: block" %>
    <%= form.collection_select :unidade_id, Unidade.all, :id, :nome, prompt: "Selecione uma unidade" %>
  </div>
  
  <div class="field">
    <%= form.label :setor_id, style: "display: block" %>
    <%= form.collection_select :setor_id, Setor.all, :id, :nome, prompt: "Selecione um Setor" %>
  </div>

  <div class="field">
    <%= form.label :cargo_id, style: "display: block" %>
    <%= form.collection_select :cargo_id, Cargo.all, :id, :nome, prompt: "Selecione um cargo" %>
  </div>

  <div class="field">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/funcionarios/_funcionario.html.erb
<div id="<%= dom_id funcionario %>">
  <p>
    <strong>Nome:</strong>
    <%= funcionario.nome %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= funcionario.cpf %>
  </p>

  <p>
    <strong>Rg:</strong>
    <%= funcionario.rg %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= funcionario.telefone %>
  </p>

  <p>
    <strong>Secretaria:</strong>
    <%= funcionario.setor.nome%>
  </p>

  <p>
    <strong>Unidade:</strong>
    <%= funcionario.unidade.nome%>
  </p>

  <p>
    <strong>Setor:</strong>
    <%= funcionario.setor.nome%>
  </p>

  <p>
    <strong>Cargo:</strong>
    <%= funcionario.cargo.nome%>
  </p>

</div>

app/views/funcionarios/edit.html.erb
<h1>Editar Funcionário</h1>

<%= render "form", funcionario: @funcionario %>

<br>

<div>
  <%= link_to "Visualizar Funcionário", admin_funcionario_path(@funcionario) %> |
  <%= link_to "Voltar para todos os Funcionários", admin_funcionarios_path %>
</div>

app/views/funcionarios/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Funcionários</h1>

<div id="funcionarios">
  <% @funcionarios.each do |funcionario| %>
    <%= render funcionario %>
    <p>
      <%= link_to "Visualizar Funcionário", admin_funcionario_path(funcionario) %>
    </p>
  <% end %>
</div>

<%= link_to "Criar novo Funcionário", new_admin_funcionario_path %>
<br>
<br>
<%= link_to "Voltar para página Inicial", admin_path %>

app/views/funcionarios/new.html.erb
<h1>Novo Funcionário</h1>

<%= render "form", funcionario: @funcionario %>

<br>

<div>
  <%= link_to "Voltar para todos os Funcionários", admin_funcionarios_path %>
</div>

app/views/funcionarios/show.html.erb
<p style="color: green"><%= notice %></p>

<h1>Dados do Funcionário</h1>

<p><strong>Nome:</strong> <%= @funcionario.nome %></p>
<p><strong>CPF:</strong> <%= @funcionario.cpf %></p>
<p><strong>RG:</strong> <%= @funcionario.rg %></p>
<p><strong>Telefone:</strong> <%= @funcionario.telefone %></p>
<p><strong>Secretaria:</strong> <%= @funcionario.secretaria.nome %></p>
<p><strong>Unidade:</strong> <%= @funcionario.unidade.nome %></p>
<p><strong>Setor:</strong> <%= @funcionario.setor.nome %></p>
<p><strong>Cargo:</strong> <%= @funcionario.cargo.nome %></p>

<div>
  <%= link_to "Editar esse Funcionário", edit_admin_funcionario_path(@funcionario) %> |
  <%= link_to "Voltar para todos os Funcionários", admin_funcionarios_path %>

  <%= button_to "Excluir Funcionário", admin_funcionario_path(@funcionario), method: :delete %>
</div>